[project]
name = "pydantic-utils"
version = "0.1.0"
description = "Pydantic utilities and extensions."
readme = "README.md"
authors = [{ name = "Philip Chung", email = "philip.f.chung@gmail.com" }]
requires-python = ">=3.11.4"
dependencies = [
 "pydantic>=2.10.3",
]

[tool.uv.sources]
utils = { workspace = true }
rag = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
