[project]
name = "irr_metrics"
version = "0.1.0"
description = "Interrater agreement metrics."
readme = "README.md"
authors = [{ name = "Philip Chung", email = "philip.f.chung@gmail.com" }]
requires-python = ">=3.11.4"
dependencies = [
    "irrcac>=0.4.4",
    "krippendorff>=0.8.0",
    "numpy>=1.26.4",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pingouin>=0.5.5",
    "pydantic>=2.10.3",
    "scikit-learn>=1.6.1",
    "scipy>=1.12.0",
]

[tool.uv.sources]
utils = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
