[project]
name = "rag"
version = "0.1.0"
description = "Custom Llama-Index code for RAG."
readme = "README.md"
authors = [{ name = "Philip Chung", email = "philip.f.chung@gmail.com" }]
requires-python = ">=3.11.4"
dependencies = [
    "llama-index>=0.12.4, <=0.12.5",
    "llama-index-core>=0.12.4, <=0.12.5",
    "llama-index-embeddings-huggingface>=0.4.0",
    "llama-index-llms-azure-openai>=0.3.0",
    "llama-index-llms-huggingface>=0.4.0",
    "llama-index-llms-openai>=0.3.0",
    "llama-index-llms-openai-like>=0.3.0",
    "llama-index-vector-stores-qdrant>=0.4.0",
    "pydantic>=2.10.3",
    "qdrant-client>=1.12.1",
]

[tool.uv.sources]
pydantic_utils = { workspace = true }
utils = { workspace = true }
rag = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
