[project]
name = "rq-utils"
version = "0.1.0"
description = "Helper functions for Redis Queue (RQ)."
readme = "README.md"
authors = [{ name = "Philip Chung", email = "philip.f.chung@gmail.com" }]
requires-python = ">=3.11.4"
dependencies = [
    "redis>=5.2.1",
    "rq>=1.16.2,<2.0.0",
    "rq-dashboard>=0.8.2.2",
    "setproctitle>=1.3.4",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
