# prometheus.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: vllm
    static_configs:
      - targets:
          - "host.docker.internal:8000"
          - "host.docker.internal:8100"
          - "host.docker.internal:8101"
          - "host.docker.internal:8102"
          - "host.docker.internal:8103"
          - "host.docker.internal:8104"
          - "host.docker.internal:8105"
